from serializer import *

# just some notes biar gausah ngescroll:
# user: id(int), nama(varchar, 20), umur(int)
# data user ada 70
# product: id(int), nama(varchar, 30), harga(int)
# data product ada 70
# order: id(int), user_id(int), product_id(int), quantity(int), total_harga(int)
# data order ada 69
# review: id(int), user_id(int), product_id(int), rating(float), comment(varchar, 255)
# data review ada 51
# order_payment: id(int), order_id(int), payment_method(varchar, 20), status(varchar, 15), payment_date(char, 20)
# data order_payment ada 60

schema_users = {
    "table_name": "users",
    "columns": [
        {"name": "user_id", "type": "int"},
        {"name": "nama", "type": "varchar", "length": 20},
        {"name": "umur", "type": "int"},
    ],
}

schema_products = {
    "table_name": "products",
    "columns": [
        {"name": "product_id", "type": "int"},
        {"name": "nama", "type": "varchar", "length": 30},
        {"name": "harga", "type": "int"},
    ],
}

schema_orders = {
    "table_name": "orders",
    "columns": [
        {"name": "order_id", "type": "int"},
        {"name": "user_id", "type": "int"},  # Referencing the users table
        {"name": "product_id", "type": "int"},  # Referencing the products table
        {"name": "quantity", "type": "int"},
        {"name": "total_harga", "type": "int"},
    ],
}

schema_reviews = {
    "table_name": "reviews",
    "columns": [
        {"name": "review_id", "type": "int"},
        {"name": "user_id", "type": "int"},  # Referencing the users table
        {"name": "product_id", "type": "int"},  # Referencing the products table
        {"name": "rating", "type": "float"},
        {"name": "comment", "type": "varchar", "length": 255},
    ],
}

schema_order_payments = {
    "table_name": "order_payments",
    "columns": [
        {"name": "order_payment_id", "type": "int"},
        {"name": "order_id", "type": "int"},  # Referencing the orders table
        {"name": "payment_method", "type": "varchar", "length": 20},
        {"name": "status", "type": "varchar", "length": 15},
        {"name": "payment_date", "type": "char", "length": 20},
    ],
}


rows_users = [
    {"user_id": 1, "nama": "Yulia", "umur": 35},
    {"user_id": 2, "nama": "Lina", "umur": 50},
    {"user_id": 3, "nama": "Duke", "umur": 50},
    {"user_id": 4, "nama": "Nia", "umur": 38},
    {"user_id": 5, "nama": "Aldo", "umur": 58},
    {"user_id": 6, "nama": "Gilang", "umur": 19},
    {"user_id": 7, "nama": "Rena", "umur": 20},
    {"user_id": 8, "nama": "Gilang", "umur": 31},
    {"user_id": 9, "nama": "Putri", "umur": 39},
    {"user_id": 10, "nama": "Amin", "umur": 50},
    {"user_id": 11, "nama": "Basudara", "umur": 60},
    {"user_id": 12, "nama": "Bella", "umur": 54},
    {"user_id": 13, "nama": "Lina", "umur": 37},
    {"user_id": 14, "nama": "Windah", "umur": 41},
    {"user_id": 15, "nama": "Bobby", "umur": 42},
    {"user_id": 16, "nama": "David", "umur": 25},
    {"user_id": 17, "nama": "Satria", "umur": 18},
    {"user_id": 18, "nama": "Joko", "umur": 28},
    {"user_id": 19, "nama": "Aditya", "umur": 29},
    {"user_id": 20, "nama": "Sandi", "umur": 48},
    {"user_id": 21, "nama": "Windah", "umur": 46},
    {"user_id": 22, "nama": "Alam", "umur": 22},
    {"user_id": 23, "nama": "Aulia", "umur": 54},
    {"user_id": 24, "nama": "Arina", "umur": 28},
    {"user_id": 25, "nama": "Meira", "umur": 38},
    {"user_id": 26, "nama": "Rena", "umur": 60},
    {"user_id": 27, "nama": "Samantha", "umur": 52},
    {"user_id": 28, "nama": "Mukti", "umur": 52},
    {"user_id": 29, "nama": "Lina", "umur": 30},
    {"user_id": 30, "nama": "Satria", "umur": 60},
    {"user_id": 31, "nama": "Aditya", "umur": 31},
    {"user_id": 32, "nama": "Bowo", "umur": 29},
    {"user_id": 33, "nama": "Mukti", "umur": 56},
    {"user_id": 34, "nama": "Ayu", "umur": 34},
    {"user_id": 35, "nama": "Rudi", "umur": 38},
    {"user_id": 36, "nama": "Aldo", "umur": 58},
    {"user_id": 37, "nama": "Taufik", "umur": 47},
    {"user_id": 38, "nama": "Tari", "umur": 32},
    {"user_id": 39, "nama": "Tito", "umur": 50},
    {"user_id": 40, "nama": "Nadia", "umur": 58},
    {"user_id": 41, "nama": "Eka", "umur": 59},
    {"user_id": 42, "nama": "Omar", "umur": 57},
    {"user_id": 43, "nama": "Duke", "umur": 32},
    {"user_id": 44, "nama": "Duke", "umur": 52},
    {"user_id": 45, "nama": "Gilang", "umur": 51},
    {"user_id": 46, "nama": "Mila", "umur": 44},
    {"user_id": 47, "nama": "Shandy", "umur": 44},
    {"user_id": 48, "nama": "Riko", "umur": 43},
    {"user_id": 49, "nama": "Mila", "umur": 32},
    {"user_id": 50, "nama": "Farhan", "umur": 31},
    {"user_id": 51, "nama": "Budi", "umur": 44},
    {"user_id": 52, "nama": "Eka", "umur": 48},
    {"user_id": 53, "nama": "Vino", "umur": 18},
    {"user_id": 54, "nama": "Farida", "umur": 49},
    {"user_id": 55, "nama": "Vino", "umur": 49},
    {"user_id": 56, "nama": "Nia", "umur": 30},
    {"user_id": 57, "nama": "Rudi", "umur": 18},
    {"user_id": 58, "nama": "Rudi", "umur": 40},
    {"user_id": 59, "nama": "Rena", "umur": 49},
    {"user_id": 60, "nama": "Edy", "umur": 28},
    {"user_id": 61, "nama": "Samantha", "umur": 55},
    {"user_id": 62, "nama": "Meira", "umur": 49},
    {"user_id": 63, "nama": "Joko", "umur": 43},
    {"user_id": 64, "nama": "Bella", "umur": 45},
    {"user_id": 65, "nama": "Riko", "umur": 30},
    {"user_id": 66, "nama": "Rama", "umur": 25},
    {"user_id": 67, "nama": "Nadia", "umur": 44},
    {"user_id": 68, "nama": "Tito", "umur": 45},
    {"user_id": 69, "nama": "Nia", "umur": 45},
    {"user_id": 70, "nama": "Bobby", "umur": 52},
]

rows_products = [
    {"product_id": 1, "nama": "V60", "harga": 20540},
    {"product_id": 2, "nama": "Donat", "harga": 14031},
    {"product_id": 3, "nama": "Dimsum", "harga": 12207},
    {"product_id": 4, "nama": "Pisang Goreng", "harga": 33210},
    {"product_id": 5, "nama": "Tahu Gejrot", "harga": 11496},
    {"product_id": 6, "nama": "Tahu Tempe", "harga": 47469},
    {"product_id": 7, "nama": "Es Campur", "harga": 46840},
    {"product_id": 8, "nama": "Dimsum", "harga": 11868},
    {"product_id": 9, "nama": "Pizza", "harga": 45104},
    {"product_id": 10, "nama": "Affogato", "harga": 6831},
    {"product_id": 11, "nama": "Lapis Legit", "harga": 6216},
    {"product_id": 12, "nama": "Burger", "harga": 40579},
    {"product_id": 13, "nama": "Lapis Legit", "harga": 46022},
    {"product_id": 14, "nama": "Soto Ayam", "harga": 45072},
    {"product_id": 15, "nama": "Steak", "harga": 34159},
    {"product_id": 16, "nama": "Kue Cubir", "harga": 27569},
    {"product_id": 17, "nama": "Sate", "harga": 14057},
    {"product_id": 18, "nama": "Pempek", "harga": 47104},
    {"product_id": 19, "nama": "Siomay", "harga": 7759},
    {"product_id": 20, "nama": "Pisang Goreng", "harga": 27806},
    {"product_id": 21, "nama": "Flat White", "harga": 5500},
    {"product_id": 22, "nama": "Pecel Lele", "harga": 45875},
    {"product_id": 23, "nama": "Tahu Saus Kacang", "harga": 46992},
    {"product_id": 24, "nama": "Kue Cubir", "harga": 6666},
    {"product_id": 25, "nama": "V60", "harga": 45048},
    {"product_id": 26, "nama": "Coto Makassar", "harga": 18438},
    {"product_id": 27, "nama": "Lontong Sayur", "harga": 9956},
    {"product_id": 28, "nama": "Pizza", "harga": 3046},
    {"product_id": 29, "nama": "Rendang", "harga": 14534},
    {"product_id": 30, "nama": "Cendol", "harga": 40880},
    {"product_id": 31, "nama": "Cendol", "harga": 38545},
    {"product_id": 32, "nama": "Gulai Kambing", "harga": 18546},
    {"product_id": 33, "nama": "Gado-Gado", "harga": 31916},
    {"product_id": 34, "nama": "Pempek", "harga": 19374},
    {"product_id": 35, "nama": "Latte", "harga": 26501},
    {"product_id": 36, "nama": "Affogato", "harga": 6671},
    {"product_id": 37, "nama": "Kue Cubir", "harga": 37550},
    {"product_id": 38, "nama": "Mochaccino", "harga": 40779},
    {"product_id": 39, "nama": "Pempek", "harga": 32618},
    {"product_id": 40, "nama": "Espresso", "harga": 3474},
    {"product_id": 41, "nama": "Chicken Wings", "harga": 19569},
    {"product_id": 42, "nama": "Nasi Goreng", "harga": 36927},
    {"product_id": 43, "nama": "Kebab", "harga": 30799},
    {"product_id": 44, "nama": "Pempek", "harga": 49866},
    {"product_id": 45, "nama": "Roti Sisir", "harga": 4693},
    {"product_id": 46, "nama": "Dimsum", "harga": 3507},
    {"product_id": 47, "nama": "Roti Sisir", "harga": 45069},
    {"product_id": 48, "nama": "Dimsum", "harga": 42385},
    {"product_id": 49, "nama": "Lasagna", "harga": 17002},
    {"product_id": 50, "nama": "Roti Bakar", "harga": 1488},
    {"product_id": 51, "nama": "Donat", "harga": 32581},
    {"product_id": 52, "nama": "Soto Betawi", "harga": 38986},
    {"product_id": 53, "nama": "Tumis Kangkung", "harga": 41840},
    {"product_id": 54, "nama": "Lontong Sayur", "harga": 32351},
    {"product_id": 55, "nama": "Tongseng", "harga": 40614},
    {"product_id": 56, "nama": "Ayam Penyet", "harga": 22062},
    {"product_id": 57, "nama": "Rendang", "harga": 19127},
    {"product_id": 58, "nama": "Kue Cubir", "harga": 37045},
    {"product_id": 59, "nama": "Kopi Susu", "harga": 49586},
    {"product_id": 60, "nama": "Mie Ayam", "harga": 6609},
    {"product_id": 61, "nama": "Soto Betawi", "harga": 8035},
    {"product_id": 62, "nama": "Dendeng Balado", "harga": 49779},
    {"product_id": 63, "nama": "Coto Makassar", "harga": 28650},
    {"product_id": 64, "nama": "Tahu Tempe", "harga": 40627},
    {"product_id": 65, "nama": "Tumis Kangkung", "harga": 11014},
    {"product_id": 66, "nama": "Flat White", "harga": 26498},
    {"product_id": 67, "nama": "Bakso", "harga": 46018},
    {"product_id": 68, "nama": "Bubur Ketan Hitam", "harga": 7643},
    {"product_id": 69, "nama": "Es Campur", "harga": 27011},
    {"product_id": 70, "nama": "Mochaccino", "harga": 35068},
]

rows_orders = [
    {"order_id": 1, "user_id": 58, "product_id": 52, "quantity": 4, "total_harga": 25183},
    {"order_id": 2, "user_id": 57, "product_id": 56, "quantity": 10, "total_harga": 10948},
    {"order_id": 3, "user_id": 49, "product_id": 28, "quantity": 10, "total_harga": 37591},
    {"order_id": 4, "user_id": 7, "product_id": 68, "quantity": 7, "total_harga": 11771},
    {"order_id": 5, "user_id": 17, "product_id": 3, "quantity": 7, "total_harga": 42033},
    {"order_id": 6, "user_id": 27, "product_id": 65, "quantity": 8, "total_harga": 13351},
    {"order_id": 7, "user_id": 28, "product_id": 68, "quantity": 4, "total_harga": 20803},
    {"order_id": 8, "user_id": 23, "product_id": 30, "quantity": 3, "total_harga": 1281},
    {"order_id": 9, "user_id": 3, "product_id": 70, "quantity": 1, "total_harga": 7733},
    {"order_id": 10, "user_id": 59, "product_id": 53, "quantity": 3, "total_harga": 20805},
    {"order_id": 11, "user_id": 11, "product_id": 46, "quantity": 9, "total_harga": 40888},
    {"order_id": 12, "user_id": 56, "product_id": 15, "quantity": 1, "total_harga": 12276},
    {"order_id": 13, "user_id": 38, "product_id": 62, "quantity": 4, "total_harga": 49027},
    {"order_id": 14, "user_id": 20, "product_id": 50, "quantity": 5, "total_harga": 25560},
    {"order_id": 15, "user_id": 13, "product_id": 40, "quantity": 4, "total_harga": 10905},
    {"order_id": 16, "user_id": 38, "product_id": 50, "quantity": 1, "total_harga": 38745},
    {"order_id": 17, "user_id": 12, "product_id": 9, "quantity": 5, "total_harga": 8975},
    {"order_id": 18, "user_id": 56, "product_id": 26, "quantity": 10, "total_harga": 14316},
    {"order_id": 19, "user_id": 32, "product_id": 22, "quantity": 3, "total_harga": 21756},
    {"order_id": 20, "user_id": 22, "product_id": 27, "quantity": 3, "total_harga": 34884},
    {"order_id": 21, "user_id": 58, "product_id": 19, "quantity": 9, "total_harga": 38502},
    {"order_id": 22, "user_id": 45, "product_id": 17, "quantity": 4, "total_harga": 2814},
    {"order_id": 23, "user_id": 46, "product_id": 63, "quantity": 6, "total_harga": 5522},
    {"order_id": 24, "user_id": 48, "product_id": 2, "quantity": 10, "total_harga": 18619},
    {"order_id": 25, "user_id": 58, "product_id": 64, "quantity": 3, "total_harga": 29541},
    {"order_id": 26, "user_id": 43, "product_id": 64, "quantity": 6, "total_harga": 45118},
    {"order_id": 27, "user_id": 55, "product_id": 48, "quantity": 4, "total_harga": 28857},
    {"order_id": 28, "user_id": 16, "product_id": 34, "quantity": 7, "total_harga": 32718},
    {"order_id": 29, "user_id": 42, "product_id": 55, "quantity": 10, "total_harga": 43158},
    {"order_id": 30, "user_id": 37, "product_id": 12, "quantity": 5, "total_harga": 31907},
    {"order_id": 31, "user_id": 49, "product_id": 58, "quantity": 2, "total_harga": 33715},
    {"order_id": 32, "user_id": 31, "product_id": 1, "quantity": 10, "total_harga": 42852},
    {"order_id": 33, "user_id": 47, "product_id": 55, "quantity": 8, "total_harga": 32461},
    {"order_id": 34, "user_id": 8, "product_id": 60, "quantity": 3, "total_harga": 23689},
    {"order_id": 35, "user_id": 33, "product_id": 62, "quantity": 6, "total_harga": 46872},
    {"order_id": 36, "user_id": 55, "product_id": 27, "quantity": 9, "total_harga": 17543},
    {"order_id": 37, "user_id": 34, "product_id": 66, "quantity": 10, "total_harga": 24957},
    {"order_id": 38, "user_id": 3, "product_id": 1, "quantity": 6, "total_harga": 13467},
    {"order_id": 39, "user_id": 10, "product_id": 68, "quantity": 2, "total_harga": 46102},
    {"order_id": 40, "user_id": 21, "product_id": 2, "quantity": 9, "total_harga": 49064},
    {"order_id": 41, "user_id": 48, "product_id": 31, "quantity": 8, "total_harga": 18321},
    {"order_id": 42, "user_id": 22, "product_id": 45, "quantity": 5, "total_harga": 29761},
    {"order_id": 43, "user_id": 17, "product_id": 7, "quantity": 10, "total_harga": 29934},
    {"order_id": 44, "user_id": 33, "product_id": 51, "quantity": 5, "total_harga": 42559},
    {"order_id": 45, "user_id": 8, "product_id": 10, "quantity": 6, "total_harga": 22713},
    {"order_id": 46, "user_id": 55, "product_id": 24, "quantity": 8, "total_harga": 45828},
    {"order_id": 47, "user_id": 23, "product_id": 16, "quantity": 4, "total_harga": 37425},
    {"order_id": 48, "user_id": 39, "product_id": 69, "quantity": 5, "total_harga": 28561},
    {"order_id": 49, "user_id": 22, "product_id": 23, "quantity": 5, "total_harga": 24159},
    {"order_id": 50, "user_id": 58, "product_id": 28, "quantity": 1, "total_harga": 42262},
    {"order_id": 51, "user_id": 34, "product_id": 50, "quantity": 3, "total_harga": 32167},
    {"order_id": 52, "user_id": 28, "product_id": 35, "quantity": 8, "total_harga": 10828},
    {"order_id": 53, "user_id": 8, "product_id": 66, "quantity": 2, "total_harga": 33513},
    {"order_id": 54, "user_id": 5, "product_id": 5, "quantity": 1, "total_harga": 31223},
    {"order_id": 55, "user_id": 3, "product_id": 68, "quantity": 1, "total_harga": 48075},
    {"order_id": 56, "user_id": 57, "product_id": 29, "quantity": 6, "total_harga": 12684},
    {"order_id": 57, "user_id": 14, "product_id": 60, "quantity": 1, "total_harga": 25793},
    {"order_id": 58, "user_id": 37, "product_id": 25, "quantity": 1, "total_harga": 33688},
    {"order_id": 59, "user_id": 47, "product_id": 49, "quantity": 10, "total_harga": 29562},
    {"order_id": 60, "user_id": 26, "product_id": 41, "quantity": 8, "total_harga": 47933},
    {"order_id": 61, "user_id": 65, "product_id": 23, "quantity": 1, "total_harga": 8354},
    {"order_id": 62, "user_id": 15, "product_id": 18, "quantity": 7, "total_harga": 36969},
    {"order_id": 63, "user_id": 22, "product_id": 20, "quantity": 2, "total_harga": 3327},
    {"order_id": 64, "user_id": 33, "product_id": 50, "quantity": 2, "total_harga": 15769},
    {"order_id": 65, "user_id": 58, "product_id": 40, "quantity": 10, "total_harga": 48809},
    {"order_id": 66, "user_id": 21, "product_id": 69, "quantity": 10, "total_harga": 28770},
    {"order_id": 67, "user_id": 44, "product_id": 58, "quantity": 4, "total_harga": 19119},
    {"order_id": 68, "user_id": 16, "product_id": 51, "quantity": 10, "total_harga": 45699},
    {"order_id": 69, "user_id": 16, "product_id": 43, "quantity": 4, "total_harga": 32065},
]

rows_reviews = [
    {
        "review_id": 1,
        "user_id": 10,
        "product_id": 5,
        "rating": 4,
        "comment": "Great product, highly recommend!",
    },
    {
        "review_id": 2,
        "user_id": 23,
        "product_id": 12,
        "rating": 3,
        "comment": "Product is okay, could be better.",
    },
    {
        "review_id": 3,
        "user_id": 7,
        "product_id": 8,
        "rating": 5,
        "comment": "Excellent product, exceeded expectations!",
    },
    {
        "review_id": 4,
        "user_id": 15,
        "product_id": 2,
        "rating": 2,
        "comment": "Disappointed with the quality.",
    },
    {
        "review_id": 5,
        "user_id": 3,
        "product_id": 18,
        "rating": 4,
        "comment": "Good product, but a bit overpriced.",
    },
    {
        "review_id": 6,
        "user_id": 28,
        "product_id": 11,
        "rating": 5,
        "comment": "Love this product! Best purchase ever.",
    },
    {
        "review_id": 7,
        "user_id": 19,
        "product_id": 4,
        "rating": 3,
        "comment": "Product is as described, but not wowed.",
    },
    {
        "review_id": 8,
        "user_id": 32,
        "product_id": 25,
        "rating": 4,
        "comment": "Solid product, worth the money.",
    },
    {
        "review_id": 9,
        "user_id": 4,
        "product_id": 17,
        "rating": 2,
        "comment": "Not impressed, would not buy again.",
    },
    {
        "review_id": 10,
        "user_id": 21,
        "product_id": 9,
        "rating": 5,
        "comment": "Amazing product, highly recommend!",
    },
    {
        "review_id": 11,
        "user_id": 13,
        "product_id": 6,
        "rating": 3,
        "comment": "Product is okay, but could use improvement.",
    },
    {
        "review_id": 12,
        "user_id": 35,
        "product_id": 14,
        "rating": 4,
        "comment": "Good product, but a bit overpriced.",
    },
    {
        "review_id": 13,
        "user_id": 27,
        "product_id": 22,
        "rating": 5,
        "comment": "Love this product! Best purchase ever.",
    },
    {
        "review_id": 14,
        "user_id": 18,
        "product_id": 3,
        "rating": 3,
        "comment": "Product is as described, but not wowed.",
    },
    {
        "review_id": 15,
        "user_id": 31,
        "product_id": 20,
        "rating": 4,
        "comment": "Solid product, worth the money.",
    },
    {
        "review_id": 16,
        "user_id": 2,
        "product_id": 16,
        "rating": 2,
        "comment": "Not impressed, would not buy again.",
    },
    {
        "review_id": 17,
        "user_id": 24,
        "product_id": 7,
        "rating": 5,
        "comment": "Amazing product, highly recommend!",
    },
    {
        "review_id": 18,
        "user_id": 11,
        "product_id": 10,
        "rating": 3,
        "comment": "Product is okay, but could use improvement.",
    },
    {
        "review_id": 19,
        "user_id": 34,
        "product_id": 19,
        "rating": 4,
        "comment": "Good product, but a bit overpriced.",
    },
    {
        "review_id": 20,
        "user_id": 26,
        "product_id": 23,
        "rating": 5,
        "comment": "Love this product! Best purchase ever.",
    },
    {
        "review_id": 21,
        "user_id": 17,
        "product_id": 1,
        "rating": 3,
        "comment": "Product is as described, but not wowed.",
    },
    {
        "review_id": 22,
        "user_id": 30,
        "product_id": 24,
        "rating": 4,
        "comment": "Solid product, worth the money.",
    },
    {
        "review_id": 23,
        "user_id": 5,
        "product_id": 15,
        "rating": 2,
        "comment": "Not impressed, would not buy again.",
    },
    {
        "review_id": 24,
        "user_id": 22,
        "product_id": 8,
        "rating": 5,
        "comment": "Amazing product, highly recommend!",
    },
    {
        "review_id": 25,
        "user_id": 10,
        "product_id": 13,
        "rating": 3,
        "comment": "Product is okay, but could use improvement.",
    },
    {
        "review_id": 26,
        "user_id": 33,
        "product_id": 21,
        "rating": 4,
        "comment": "Good product, but a bit overpriced.",
    },
    {
        "review_id": 27,
        "user_id": 25,
        "product_id": 29,
        "rating": 5,
        "comment": "Love this product! Best purchase ever.",
    },
    {
        "review_id": 28,
        "user_id": 16,
        "product_id": 2,
        "rating": 3,
        "comment": "Product is as described, but not wowed.",
    },
    {
        "review_id": 29,
        "user_id": 29,
        "product_id": 18,
        "rating": 4,
        "comment": "Solid product, worth the money.",
    },
    {
        "review_id": 30,
        "user_id": 4,
        "product_id": 12,
        "rating": 2,
        "comment": "Not impressed, would not buy again.",
    },
    {
        "review_id": 31,
        "user_id": 20,
        "product_id": 7,
        "rating": 5,
        "comment": "Amazing product, highly recommend!",
    },
    {
        "review_id": 32,
        "user_id": 9,
        "product_id": 11,
        "rating": 3,
        "comment": "Product is okay, but could use improvement.",
    },
    {
        "review_id": 33,
        "user_id": 32,
        "product_id": 25,
        "rating": 4,
        "comment": "Good product, but a bit overpriced.",
    },
    {
        "review_id": 34,
        "user_id": 28,
        "product_id": 17,
        "rating": 5,
        "comment": "Love this product! Best purchase ever.",
    },
    {
        "review_id": 35,
        "user_id": 15,
        "product_id": 3,
        "rating": 3,
        "comment": "Product is as described, but not wowed.",
    },
    {
        "review_id": 36,
        "user_id": 27,
        "product_id": 20,
        "rating": 4,
        "comment": "Solid product, worth the money.",
    },
    {
        "review_id": 37,
        "user_id": 1,
        "product_id": 16,
        "rating": 2,
        "comment": "Not impressed, would not buy again.",
    },
    {
        "review_id": 38,
        "user_id": 23,
        "product_id": 9,
        "rating": 5,
        "comment": "Amazing product, highly recommend!",
    },
    {
        "review_id": 39,
        "user_id": 7,
        "product_id": 14,
        "rating": 3,
        "comment": "Product is okay, but could use improvement.",
    },
    {
        "review_id": 40,
        "user_id": 30,
        "product_id": 22,
        "rating": 4,
        "comment": "Good product, but a bit overpriced.",
    },
    {
        "review_id": 41,
        "user_id": 24,
        "product_id": 29,
        "rating": 5,
        "comment": "Love this product! Best purchase ever.",
    },
    {
        "review_id": 42,
        "user_id": 13,
        "product_id": 2,
        "rating": 3,
        "comment": "Product is as described, but not wowed.",
    },
    {
        "review_id": 43,
        "user_id": 26,
        "product_id": 18,
        "rating": 4,
        "comment": "Solid product, worth the money.",
    },
    {
        "review_id": 44,
        "user_id": 11,
        "product_id": 12,
        "rating": 2,
        "comment": "Not impressed, would not buy again.",
    },
    {
        "review_id": 45,
        "user_id": 35,
        "product_id": 7,
        "rating": 5,
        "comment": "Amazing product, highly recommend!",
    },
    {
        "review_id": 46,
        "user_id": 17,
        "product_id": 10,
        "rating": 3,
        "comment": "Product is okay, but could use improvement.",
    },
    {
        "review_id": 47,
        "user_id": 31,
        "product_id": 19,
        "rating": 4,
        "comment": "Good product, but a bit overpriced.",
    },
    {
        "review_id": 48,
        "user_id": 5,
        "product_id": 23,
        "rating": 5,
        "comment": "Love this product! Best purchase ever.",
    },
    {
        "review_id": 49,
        "user_id": 22,
        "product_id": 1,
        "rating": 3,
        "comment": "Product is as described, but not wowed.",
    },
    {
        "review_id": 50,
        "user_id": 30,
        "product_id": 24,
        "rating": 4,
        "comment": "Solid product, worth the money.",
    },
    {
        "review_id": 51,
        "user_id": 4,
        "product_id": 15,
        "rating": 2,
        "comment": "Not impressed, would not buy again.",
    },
]

rows_order_payments = [
    {
        "order_payment_id": 1,
        "order_id": 1,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-01 08:00:00",
    },
    {
        "order_payment_id": 2,
        "order_id": 2,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-01 09:00:00",
    },
    {
        "order_payment_id": 3,
        "order_id": 3,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-01 10:00:00",
    },
    {
        "order_payment_id": 4,
        "order_id": 4,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-01 11:00:00",
    },
    {
        "order_payment_id": 5,
        "order_id": 5,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-01 12:00:00",
    },
    {
        "order_payment_id": 6,
        "order_id": 6,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-01 13:00:00",
    },
    {
        "order_payment_id": 7,
        "order_id": 7,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-01 14:00:00",
    },
    {
        "order_payment_id": 8,
        "order_id": 8,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-01 15:00:00",
    },
    {
        "order_payment_id": 9,
        "order_id": 9,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-01 16:00:00",
    },
    {
        "order_payment_id": 10,
        "order_id": 10,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-01 17:00:00",
    },
    {
        "order_payment_id": 11,
        "order_id": 11,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-01 18:00:00",
    },
    {
        "order_payment_id": 12,
        "order_id": 12,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-01 19:00:00",
    },
    {
        "order_payment_id": 13,
        "order_id": 13,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-01 20:00:00",
    },
    {
        "order_payment_id": 14,
        "order_id": 14,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-01 21:00:00",
    },
    {
        "order_payment_id": 15,
        "order_id": 15,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-01 22:00:00",
    },
    {
        "order_payment_id": 16,
        "order_id": 16,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-01 23:00:00",
    },
    {
        "order_payment_id": 17,
        "order_id": 17,
        "payment_method": "Credit Card",
        "status": "Failed",
        "payment_date": "2021-01-02 08:00:00",
    },
    {
        "order_payment_id": 18,
        "order_id": 18,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-02 09:00:00",
    },
    {
        "order_payment_id": 19,
        "order_id": 19,
        "payment_method": "Credit Card",
        "status": "Pending",
        "payment_date": "2021-01-02 10:00:00",
    },
    {
        "order_payment_id": 20,
        "order_id": 20,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-02 11:00:00",
    },
    {
        "order_payment_id": 21,
        "order_id": 21,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-02 12:00:00",
    },
    {
        "order_payment_id": 22,
        "order_id": 22,
        "payment_method": "Bank Transfer",
        "status": "Failed",
        "payment_date": "2021-01-02 13:00:00",
    },
    {
        "order_payment_id": 23,
        "order_id": 23,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-02 14:00:00",
    },
    {
        "order_payment_id": 24,
        "order_id": 24,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-02 15:00:00",
    },
    {
        "order_payment_id": 25,
        "order_id": 25,
        "payment_method": "Credit Card",
        "status": "Failed",
        "payment_date": "2021-01-02 16:00:00",
    },
    {
        "order_payment_id": 26,
        "order_id": 26,
        "payment_method": "Bank Transfer",
        "status": "Pending",
        "payment_date": "2021-01-02 17:00:00",
    },
    {
        "order_payment_id": 27,
        "order_id": 27,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-02 18:00:00",
    },
    {
        "order_payment_id": 28,
        "order_id": 28,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-02 19:00:00",
    },
    {
        "order_payment_id": 29,
        "order_id": 29,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-02 20:00:00",
    },
    {
        "order_payment_id": 30,
        "order_id": 30,
        "payment_method": "Bank Transfer",
        "status": "Failed",
        "payment_date": "2021-01-02 21:00:00",
    },
    {
        "order_payment_id": 31,
        "order_id": 31,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-02 22:00:00",
    },
    {
        "order_payment_id": 32,
        "order_id": 32,
        "payment_method": "Bank Transfer",
        "status": "Pending",
        "payment_date": "2021-01-02 23:00:00",
    },
    {
        "order_payment_id": 33,
        "order_id": 33,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-03 08:00:00",
    },
    {
        "order_payment_id": 34,
        "order_id": 34,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-03 09:00:00",
    },
    {
        "order_payment_id": 35,
        "order_id": 35,
        "payment_method": "Credit Card",
        "status": "Failed",
        "payment_date": "2021-01-03 10:00:00",
    },
    {
        "order_payment_id": 36,
        "order_id": 36,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-03 11:00:00",
    },
    {
        "order_payment_id": 37,
        "order_id": 37,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-03 12:00:00",
    },
    {
        "order_payment_id": 38,
        "order_id": 38,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-03 13:00:00",
    },
    {
        "order_payment_id": 39,
        "order_id": 39,
        "payment_method": "Credit Card",
        "status": "Pending",
        "payment_date": "2021-01-03 14:00:00",
    },
    {
        "order_payment_id": 40,
        "order_id": 40,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-03 15:00:00",
    },
    {
        "order_payment_id": 41,
        "order_id": 41,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-03 16:00:00",
    },
    {
        "order_payment_id": 42,
        "order_id": 42,
        "payment_method": "Bank Transfer",
        "status": "Failed",
        "payment_date": "2021-01-03 17:00:00",
    },
    {
        "order_payment_id": 43,
        "order_id": 43,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-03 18:00:00",
    },
    {
        "order_payment_id": 44,
        "order_id": 44,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-03 19:00:00",
    },
    {
        "order_payment_id": 45,
        "order_id": 45,
        "payment_method": "Credit Card",
        "status": "Pending",
        "payment_date": "2021-01-03 20:00:00",
    },
    {
        "order_payment_id": 46,
        "order_id": 46,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-03 21:00:00",
    },
    {
        "order_payment_id": 47,
        "order_id": 47,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-03 22:00:00",
    },
    {
        "order_payment_id": 48,
        "order_id": 48,
        "payment_method": "Bank Transfer",
        "status": "Failed",
        "payment_date": "2021-01-03 23:00:00",
    },
    {
        "order_payment_id": 49,
        "order_id": 49,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-04 08:00:00",
    },
    {
        "order_payment_id": 50,
        "order_id": 50,
        "payment_method": "Bank Transfer",
        "status": "Pending",
        "payment_date": "2021-01-04 09:00:00",
    },
    {
        "order_payment_id": 51,
        "order_id": 51,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-04 10:00:00",
    },
    {
        "order_payment_id": 52,
        "order_id": 52,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-04 11:00:00",
    },
    {
        "order_payment_id": 53,
        "order_id": 53,
        "payment_method": "Credit Card",
        "status": "Failed",
        "payment_date": "2021-01-04 12:00:00",
    },
    {
        "order_payment_id": 54,
        "order_id": 54,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-04 13:00:00",
    },
    {
        "order_payment_id": 55,
        "order_id": 55,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-04 14:00:00",
    },
    {
        "order_payment_id": 56,
        "order_id": 56,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-04 15:00:00",
    },
    {
        "order_payment_id": 57,
        "order_id": 57,
        "payment_method": "Credit Card",
        "status": "Pending",
        "payment_date": "2021-01-04 16:00:00",
    },
    {
        "order_payment_id": 58,
        "order_id": 58,
        "payment_method": "Bank Transfer",
        "status": "Success",
        "payment_date": "2021-01-04 17:00:00",
    },
    {
        "order_payment_id": 59,
        "order_id": 59,
        "payment_method": "Credit Card",
        "status": "Success",
        "payment_date": "2021-01-04 18:00:00",
    },
    {
        "order_payment_id": 60,
        "order_id": 60,
        "payment_method": "Bank Transfer",
        "status": "Failed",
        "payment_date": "2021-01-04 19:00:00",
    },
]

# buat file bytes dari data diatas menggunakan serializer

serializer = Serializer()

# buat schema
users_schema = serializer.serialize_schema(schema_users)
products_schema = serializer.serialize_schema(schema_products)
orders_schema = serializer.serialize_schema(schema_orders)
reviews_schema = serializer.serialize_schema(schema_reviews)
order_payments_schema = serializer.serialize_schema(schema_order_payments)

# buat data
users_bytes = serializer.serialize_with_blocks(rows_users, schema_users)
products_bytes = serializer.serialize_with_blocks(rows_products, schema_products)
orders_bytes = serializer.serialize_with_blocks(rows_orders, schema_orders)
reviews_bytes = serializer.serialize_with_blocks(rows_reviews, schema_reviews)
order_payments_bytes = serializer.serialize_with_blocks(
    rows_order_payments, schema_order_payments
)

#simpan data schema ke file
with open("../Storage_Manager/data/users_schema.dat", "wb") as file:
    file.write(users_schema)

with open("../Storage_Manager/data/products_schema.dat", "wb") as file:
    file.write(products_schema)

with open("../Storage_Manager/data/orders_schema.dat", "wb") as file:
    file.write(orders_schema)

with open("../Storage_Manager/data/reviews_schema.dat", "wb") as file:
    file.write(reviews_schema)

with open("../Storage_Manager/data/order_payments_schema.dat", "wb") as file:
    file.write(order_payments_schema)

# simpan data ke file
with open("../Storage_Manager/data/users.dat", "wb") as file:
    file.write(users_bytes)

with open("../Storage_Manager/data/products.dat", "wb") as file:
    file.write(products_bytes)

with open("../Storage_Manager/data/orders.dat", "wb") as file:
    file.write(orders_bytes)

with open("../Storage_Manager/data/reviews.dat", "wb") as file:
    file.write(reviews_bytes)

with open("../Storage_Manager/data/order_payments.dat", "wb") as file:
    file.write(order_payments_bytes)
